#include "src/app.h"
#include "src/screen.h"
#include "src/keyboard.h"
#include "src/edit.h"
#include "src/view.h"
#include "src/term.h"
#include "src/menu.h"
#include "src/adc_read.h"

#include "src/apps/wifilist.h"
#include "src/apps/gemini.h"
#include "src/apps/irc.h"
#include "src/apps/notes.h"
#include "src/apps/python.h"
#include "src/apps/settings.h"
